ci: Workaround alpine CI build
Alpine build is failing in CI apparently since the move to 7.1.x:

  error: objtool [signal.c:118]: init_signal_handler: sigaltstack failed: Out of memory
  make[4]: *** [/usr/src/linux-headers-7.1.5-0-stable/scripts/Makefile.build:289: mod-foo-a.o] Error 255
  make[4]: *** Deleting file 'mod-foo-a.o'

Workaround by passing -j1 when building the test modules.

Signed-off-by: Lucas De Marchi <demarchi@kernel.org>
Link: https://github.com/kmod-project/kmod/pull/454